name: test
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - uses: actions/checkout@v4
      - name: Test
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - name: Codecov
        uses: codecov/codecov-action@v5.4.2
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
